apiVersion: v1
kind: Pod
metadata:
  name: kub02-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
    - mountPath: /var/log/nginx
      name: nginx-logs
  volumes:
  - name: nginx-logs
    persistentVolumeClaim:
      claimName: prod-pvc